server:
  port: ${PORT:8070}
  
zuul:
  ignoredServices: '*'
  routes:
    order:
      path: /order/**
      url: http://localhost:7000/order

    delivery:
      path: /delivery/**
      url: http://localhost:8000/delivery      